# Generated by Django 3.2.9 on 2021-11-22 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_application_error_service_error'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Geral',
        ),
    ]
