# Generated by Django 3.2.9 on 2021-12-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, default='Customer', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nickname',
            field=models.CharField(blank=True, default='Customer', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='second_name',
            field=models.CharField(blank=True, default='Test', max_length=100, null=True),
        ),
    ]
