# Generated by Django 3.2.9 on 2021-11-28 03:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_auto_20211122_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('name', models.CharField(default='Product', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('external_code', models.CharField(max_length=25, null=True)),
                ('code_ean_gtin', models.CharField(max_length=25, null=True)),
                ('code', models.CharField(max_length=25, null=True)),
                ('sku', models.CharField(max_length=25, null=True)),
                ('price_sell', models.DecimalField(decimal_places=7, max_digits=11, null=True)),
                ('price_cost', models.DecimalField(decimal_places=7, max_digits=11, null=True)),
                ('price_promo', models.DecimalField(decimal_places=7, max_digits=11, null=True)),
                ('detail_weight', models.DecimalField(decimal_places=5, max_digits=8, null=True)),
                ('detail_length', models.DecimalField(decimal_places=5, max_digits=8, null=True)),
                ('detail_width', models.DecimalField(decimal_places=5, max_digits=8, null=True)),
                ('detail_height', models.DecimalField(decimal_places=5, max_digits=8, null=True)),
                ('active', models.BooleanField(default=False)),
                ('video_url', models.TextField(blank=True, null=True)),
                ('company_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.data')),
            ],
        ),
    ]
