# Generated by Django 3.2.9 on 2021-11-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=7, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
