# Generated by Django 3.2.9 on 2021-11-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20211129_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=11, null=True),
        ),
    ]
