# Generated by Django 3.2.9 on 2021-12-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20211203_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subtitle',
            field=models.CharField(default='Subtitle', max_length=100),
        ),
    ]
