# Generated by Django 3.2.9 on 2021-12-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_quantity',
            field=models.IntegerField(default=0, max_length=11, null=True),
        ),
    ]
