# Generated by Django 3.2.9 on 2021-12-05 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_currency'),
        ('catalog', '0006_product_sold_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.currency'),
        ),
    ]
