# Generated by Django 3.2.9 on 2021-12-05 03:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20211122_2053'),
        ('catalog', '0007_product_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('original_name', models.CharField(max_length=100)),
                ('fake_name', models.CharField(max_length=100)),
                ('url', models.TextField(blank=True, null=True)),
                ('image_format', models.CharField(choices=[('1', 'JPG'), ('2', 'JPEG'), ('3', 'PNG')], max_length=1, null=True)),
                ('active', models.BooleanField(default=False)),
                ('main', models.BooleanField(default=False)),
                ('company_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.data')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
            ],
        ),
    ]
