# Generated by Django 3.2.9 on 2021-12-05 03:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20211122_2053'),
        ('catalog', '0008_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('name', models.CharField(default='Category', max_length=100)),
                ('code', models.CharField(max_length=25, null=True)),
                ('company_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.data')),
            ],
        ),
    ]
