# Generated by Django 3.2.9 on 2021-12-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sold_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
