# Generated by Django 3.2.9 on 2021-12-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_product_sold_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('1', 'New'), ('2', 'Used')], max_length=1, null=True),
        ),
    ]
