# Generated by Django 3.2.9 on 2021-12-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty_option',
            field=models.CharField(choices=[('1', 'Seller warranty'), ('2', 'Factory warranty'), ('2', 'No warranty')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_time',
            field=models.CharField(choices=[('1', 'Days'), ('2', 'Months'), ('2', 'Years')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_value',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
