# Generated by Django 3.2.9 on 2021-12-14 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20211213_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Catalog Category', 'verbose_name_plural': 'Catalog Category'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Catalog Image', 'verbose_name_plural': 'Catalog Image'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Catalog Product', 'verbose_name_plural': 'Catalog Product'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Catalog Setting', 'verbose_name_plural': 'Catalog Setting'},
        ),
    ]
