# Generated by Django 3.2.9 on 2021-12-27 03:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20211214_2105'),
        ('catalog', '0017_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('name', models.CharField(default='Standard', max_length=25)),
                ('code', models.CharField(max_length=5, null=True)),
                ('company_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.companydata')),
            ],
            options={
                'verbose_name': 'Catalog Stock Locale',
                'verbose_name_plural': 'Catalog Stock Locale',
                'db_table': 'catalog_stock_locale',
            },
        ),
    ]
