# Generated by Django 3.2.9 on 2021-12-27 03:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20211214_2105'),
        ('catalog', '0018_stocklocale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(default=datetime.datetime.now)),
                ('type', models.CharField(choices=[('1', 'Other'), ('2', 'Input'), ('3', 'Exit'), ('4', 'Sale'), ('5', 'Purchase'), ('6', 'Devolution')], default=1, max_length=1)),
                ('model_class', models.CharField(max_length=15, null=True)),
                ('model_id', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('new_stock', models.IntegerField(null=True)),
                ('company_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.companydata')),
                ('stock_locale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.stocklocale')),
            ],
            options={
                'verbose_name': 'Catalog Stock',
                'verbose_name_plural': 'Catalog Stock',
                'db_table': 'catalog_stock',
            },
        ),
    ]
