# Generated by Django 3.2.9 on 2021-12-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_stock_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='model_class',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='stock',
            name='model_id',
            field=models.IntegerField(),
        ),
    ]
