# Generated by Django 3.2.9 on 2021-12-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20211227_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='model_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
