# Generated by Django 3.2.9 on 2021-12-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_alter_stock_model_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
