# Generated by Django 3.2.9 on 2021-12-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_remove_stock_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklocale',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
