# Generated by Django 3.2.9 on 2021-12-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_stocklocale_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklocale',
            name='code',
            field=models.CharField(default='STD', max_length=5, null=True),
        ),
    ]
