# Generated by Django 3.2.9 on 2021-12-22 09:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0011_auto_20211214_2105'),
        ('application', '0004_auto_20211213_2217'),
        ('catalog', '0016_auto_20211213_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('status', models.BooleanField(default=False)),
                ('application_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.applicationlink')),
                ('company_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.companydata')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Ads Link',
                'verbose_name_plural': 'Ads Link',
                'db_table': 'ads_link',
            },
        ),
    ]
