# Generated by Django 3.2.9 on 2021-11-26 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='created_datetime',
            new_name='created_on',
        ),
    ]
