# Generated by Django 3.2.9 on 2021-11-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_created_on_info_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='info',
            name='code',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='code_ean_gtin',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='detail_height',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='detail_length',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='detail_weight',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='detail_width',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='external_code',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='name',
            field=models.CharField(default='Product', max_length=100),
        ),
        migrations.AddField(
            model_name='info',
            name='price_cost',
            field=models.DecimalField(decimal_places=7, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='price_promo',
            field=models.DecimalField(decimal_places=7, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='price_sell',
            field=models.DecimalField(decimal_places=7, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='sku',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='video_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
