# Generated by Django 3.2.9 on 2021-11-22 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_configuration_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='data',
            new_name='company_data',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='data',
            new_name='company_data',
        ),
    ]
