# Generated by Django 3.2.9 on 2021-12-13 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_seller'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data',
            table='company_data',
        ),
    ]
