# Generated by Django 3.2.9 on 2021-12-13 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211122_2036'),
        ('log', '0003_delete_geral'),
        ('sale', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalog', '0014_alter_product_stock'),
        ('company', '0006_alter_data_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='CompanyData',
        ),
        migrations.AlterModelTable(
            name='configuration',
            table='company_configuration',
        ),
    ]
