# Generated by Django 3.2.9 on 2021-12-13 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20211213_0442'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Configuration',
            new_name='CompanyConfiguration',
        ),
    ]
