# Generated by Django 3.2.9 on 2021-11-22 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_globalparam_param'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuration',
        ),
    ]
