# Generated by Django 3.2.9 on 2021-11-22 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_delete_configuration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Param',
            new_name='Configuration',
        ),
    ]
