# Generated by Django 3.2.9 on 2021-12-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_param_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=25)),
                ('currency_name', models.CharField(max_length=25)),
                ('code', models.CharField(max_length=5)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
