# Generated by Django 3.2.9 on 2021-12-06 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_permissions', '0001_initial'),
        ('base', '0006_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Category', max_length=100)),
                ('code', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('operation_type', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='module',
            name='code',
        ),
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='global_permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='global_permissions.globalpermission'),
        ),
        migrations.AddField(
            model_name='module',
            name='key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='value',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
