# Generated by Django 3.2.9 on 2021-12-06 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_plan_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'managed': False},
        ),
    ]
