# Generated by Django 3.2.9 on 2021-12-06 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_module_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={},
        ),
    ]
