# Generated by Django 3.2.9 on 2021-12-06 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_module_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.currency'),
        ),
    ]
