# Generated by Django 3.2.9 on 2021-12-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_paymenttype_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
