# Generated by Django 3.2.9 on 2021-12-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_paymenttype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='operation_type',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='payment_type',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
