# Generated by Django 3.2.9 on 2021-12-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20211206_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='operation_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='payment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
