# Generated by Django 3.2.9 on 2021-12-13 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_configuration_baseconfiguration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Integration',
        ),
    ]
