# Generated by Django 3.2.9 on 2021-12-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_product_stock'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('global_permissions', '0001_initial'),
        ('sale', '0001_initial'),
        ('base', '0019_auto_20211213_0506'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='BaseCategory', max_length=100)),
                ('code', models.CharField(max_length=25, null=True)),
            ],
            options={
                'db_table': 'base_category',
            },
        ),
        migrations.RenameModel(
            old_name='CreditOperator',
            new_name='BaseCreditOperator',
        ),
        migrations.RenameModel(
            old_name='Currency',
            new_name='BaseCurrency',
        ),
        migrations.RenameModel(
            old_name='Module',
            new_name='BaseModule',
        ),
        migrations.RenameModel(
            old_name='PaymentType',
            new_name='BasePaymentType',
        ),
        migrations.RenameModel(
            old_name='Plan',
            new_name='BasePlan',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
