# Generated by Django 3.2.9 on 2021-12-13 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20211213_0510'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='basecategory',
            table='base_categorye',
        ),
    ]
