# Generated by Django 3.2.9 on 2021-12-13 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_basecategory_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='basecategory',
            table='base_category',
        ),
    ]
