# Generated by Django 3.2.9 on 2021-12-14 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_basecategory_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecategory',
            options={'verbose_name': 'Base Category', 'verbose_name_plural': 'Base Category'},
        ),
        migrations.AlterModelOptions(
            name='baseconfiguration',
            options={'verbose_name': 'Base Configuration', 'verbose_name_plural': 'Base Configuration'},
        ),
        migrations.AlterModelOptions(
            name='basecreditoperator',
            options={'verbose_name': 'Base Credit Operator', 'verbose_name_plural': 'Base Credit Operator'},
        ),
        migrations.AlterModelOptions(
            name='basecurrency',
            options={'verbose_name': 'Base Currency', 'verbose_name_plural': 'Base Currency'},
        ),
        migrations.AlterModelOptions(
            name='basemodule',
            options={'verbose_name': 'Base Module', 'verbose_name_plural': 'Base Module'},
        ),
        migrations.AlterModelOptions(
            name='basepaymenttype',
            options={'verbose_name': 'Base Payment Type', 'verbose_name_plural': 'Base Payment Type'},
        ),
        migrations.AlterModelOptions(
            name='baseplan',
            options={'verbose_name': 'Base Plan', 'verbose_name_plural': 'Base Plan'},
        ),
    ]
