# Generated by Django 3.2.9 on 2021-12-15 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='seller',
            table='seller',
        ),
    ]
