# Generated by Django 3.2.9 on 2021-12-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_seller_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='first_name',
            field=models.CharField(blank=True, default='Seller', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='nickname',
            field=models.CharField(blank=True, default='Seller', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='second_name',
            field=models.CharField(blank=True, default='Test', max_length=100, null=True),
        ),
    ]
