# Generated by Django 3.2.9 on 2021-12-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20211227_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
