# Generated by Django 3.2.9 on 2021-12-14 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Item'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='parcel',
            options={'verbose_name': 'Parcel', 'verbose_name_plural': 'Parcel'},
        ),
        migrations.AlterModelOptions(
            name='parcelgroup',
            options={'verbose_name': 'Parcel Group', 'verbose_name_plural': 'Parcel Group'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payment'},
        ),
    ]
