# Generated by Django 3.2.9 on 2021-12-14 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20211213_2310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Sale Item', 'verbose_name_plural': 'Sale Item'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Sale Order', 'verbose_name_plural': 'Sale Order'},
        ),
        migrations.AlterModelOptions(
            name='parcel',
            options={'verbose_name': 'Sale Parcel', 'verbose_name_plural': 'Sale Parcel'},
        ),
        migrations.AlterModelOptions(
            name='parcelgroup',
            options={'verbose_name': 'Sale Parcel Group', 'verbose_name_plural': 'Sale Parcel Group'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Sale Payment', 'verbose_name_plural': 'Sale Payment'},
        ),
    ]
