# Generated by Django 3.2.9 on 2021-12-15 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_auto_20211214_2104'),
    ]

    operations = [

    ]
