# Generated by Django 3.2.9 on 2021-12-15 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_auto_20211214_2111'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='sale_item',
        ),
        migrations.AlterModelTable(
            name='order',
            table='sale_order',
        ),
        migrations.AlterModelTable(
            name='parcel',
            table='sale_parcel',
        ),
        migrations.AlterModelTable(
            name='parcelgroup',
            table='sale_parcel_group',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='sale_payment',
        ),
    ]
