# Generated by Django 3.2.9 on 2021-12-31 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20211227_0113'),
        ('seller', '0004_seller_main'),
        ('sale', '0008_auto_20211231_1724'),
    ]

    operations = [

    ]
