# Generated by Django 3.2.9 on 2021-12-31 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20211227_0113'),
        ('seller', '0004_seller_main'),
        ('sale', '0008_auto_20211231_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cutomer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seller.seller'),
        ),
    ]
