# Generated by Django 3.2.9 on 2021-12-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisinglink',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
