# Generated by Django 3.2.9 on 2021-12-13 07:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20211213_0444'),
        ('application', '0002_applicationlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationlink',
            name='code',
        ),
        migrations.AddField(
            model_name='applicationlink',
            name='base_application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.baseapplication'),
        ),
        migrations.AddField(
            model_name='applicationlink',
            name='company_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.companydata'),
        ),
        migrations.AddField(
            model_name='applicationlink',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
