# Generated by Django 3.2.9 on 2021-12-14 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20211213_0454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationlink',
            options={'verbose_name': 'Application Link', 'verbose_name_plural': 'Application Link'},
        ),
        migrations.AlterModelOptions(
            name='baseapplication',
            options={'verbose_name': 'Base Application', 'verbose_name_plural': 'Base Application'},
        ),
    ]
