# Generated by Django 3.2.9 on 2021-12-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20211213_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseapplication',
            name='type',
            field=models.CharField(choices=[('1', 'Marketplace'), ('2', 'E-commerce'), ('3', 'Payment'), ('4', 'ERP')], max_length=1, null=True),
        ),
    ]
