# Generated by Django 3.2.9 on 2021-12-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_baseapplication_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseapplication',
            name='Installed',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='baseapplication',
            name='stars',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
