# Generated by Django 3.2.9 on 2021-12-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20211225_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseapplication',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
