# Generated by Django 3.2.9 on 2021-12-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_baseapplication_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseapplication',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseapplication',
            name='image_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='baseapplication',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
