# Generated by Django 3.2.9 on 2021-12-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20211225_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseapplication',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='baseapplication',
            name='image_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
