# Generated by Django 3.2.9 on 2021-12-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_alter_baseapplication_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseapplication',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
