# Generated by Django 3.2.9 on 2021-11-22 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_configuration_data'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='code',
        ),
        migrations.AddField(
            model_name='token',
            name='application',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='company_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.data'),
        ),
        migrations.AddField(
            model_name='token',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='reference',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
