# Generated by Django 3.2.9 on 2021-12-15 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211122_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'verbose_name': 'API Token', 'verbose_name_plural': 'API Token'},
        ),
    ]
